theme: jekyll-theme-minimal
title: Welcome to Renato’s homepage!
email: "rvilca100@gmail.com"
description: A place to keep an eye on some of my projects
description: [My Resume](https://rvilca.github.io/resume/)
description: My resume
